project-detail-page
rohitdasu/projectmate pull request #209
Opened 2022-10-05 16:22 UTC by AdityaPainuli

Closes #134 

### You can check it out on /projects/{any-number}
- write now it's not protected or attached route and everything is just hardcoded as of now 

### Feature I proposed - 
1. Adding a comment component to comment on a particular post 
2. Ask the user to post an image of a certain ratio to preview on the details page to make it look good. 

### Quick screenshots of the UI - 

![image](https://user-images.githubusercontent.com/66621672/194111298-ba5781e8-f935-4c7b-8c9c-cebe82372fc5.png)

![image](https://user-images.githubusercontent.com/66621672/194111321-064bee31-1c47-4077-980f-42151fe08e7c.png)

2022-10-05 16:59 UTC, rohitdasu requested changes

2022-10-05 16:59 UTC, rohitdasu commented on pages/projects/[projectId].tsx
> +      </div>
please don't hardcode, we already have the API. 
also please integrate with the flow (example on clicking of `contribute` button it should redirect to the details page)

2022-10-05 17:00 UTC, rohitdasu commented
Alignment issue ⚠️ 
<img width="446" alt="Screenshot 2022-10-05 at 10 29 54 PM" src="https://user-images.githubusercontent.com/48400770/194118664-9914238e-38ae-4dfb-aaa8-fa91ce7718fc.png">

2022-10-05 17:04 UTC, leewan-09 commented
I think the **Skill required** is not the appropriate word to use here

2022-10-06 06:12 UTC, AdityaPainuli commented
> I think the **Skill required** is not the appropriate word to use here

Yes, I am changing it with the tech stack. any better heading suggestions ??

2022-10-13 12:20 UTC, closed without merging