Recreating design look for profile page
rohitdasu/projectmate pull request #211
Opened 2022-10-07 17:29 UTC by JakubChorzepa

### Fixes Issue

Closes #135 

### Screenshots

![image](https://user-images.githubusercontent.com/74047866/194615808-7ca7fe2c-fe75-4d46-8a45-0787e9e51037.png)

2022-10-07 18:43 UTC, rohitdasu approved these changes
LGTM 👍

2022-10-07 19:20 UTC, leewan-09 requested changes
it would be nice if we change the path like this `/user/profile` instead of `/profile`.  It would look much more professional

2022-10-08 14:07 UTC, rohitdasu approved these changes

2022-10-08 17:34 UTC, leewan-09 approved these changes
LGTM 👍🏾. Well done.

2022-10-08 17:34 UTC, merged