refactored submit project form
rohitdasu/projectmate pull request #239
Opened 2022-10-19 16:34 UTC by Yazdun

### Changes proposed

The submit project page was too cluttered. I created a reusable Input component, and I completely isolated validation logic in a separate file ( single source of truth ) and pass them as prop to Input component. 

I also removed the rich text section completely, since I believe we should use markdown instead. we can save markdown as plain text in database and later, we can render markdown on the project detail page.

### Note to reviewers

> Due to Internet blackout in my country, I barely have access to internet and I wasn't able to make any API request. I implemented a fake form submission and console log the output data. Someone should take this from here and hook up the API with the form.

2022-10-19 17:43 UTC, leewan-09 requested changes
Add some margin to the bottom and top.  for the bottom, it is too less.

In my opinion, Input fields are too big in height and I don't like bold labels. 

![image](https://user-images.githubusercontent.com/60838584/196765152-002091dd-098e-46d5-971a-7e4774774d79.png)

2022-10-19 17:58 UTC, leewan-09 requested changes

2022-10-19 17:58 UTC, leewan-09 commented on components/FormElements/Input.tsx
> +import { is_form_invalid, find_input_error } from '../../utils';
@/utils/

2022-10-19 17:58 UTC, leewan-09 commented on components/FormElements/Input.tsx
> +  const inputErrors: any = find_input_error(errors, name);
1. Change to camelCase
2. Add type to this function

2022-10-19 17:58 UTC, leewan-09 commented on components/FormElements/Input.tsx
> +  onChange?: any;
Add type

2022-10-19 17:58 UTC, leewan-09 commented on components/SubmitPageForm/SubmitForm.tsx
> +} from '../../utils/input_validators';
@/utils/

2022-10-19 17:58 UTC, leewan-09 commented on components/SubmitPageForm/SubmitForm.tsx
> +  const [tags, setTags] = useState<any>([]);
missing type

2022-10-19 17:58 UTC, leewan-09 commented on components/SubmitPageForm/SubmitForm.tsx
> +    console.log({ ...formData, tags });
remove `console.log`

2022-10-19 17:58 UTC, leewan-09 commented on utils/input_validators.ts
> +export const project_name_validation = {
use camelCase and also follow the same file naming pattern.

2022-10-21 14:40 UTC, rohitdasu commented on pages/projects/submit.tsx
> +          Sumbit Your Project
```suggestion
          Submit Your Project
```

2023-02-24 17:54 UTC, rohitdasu commented
closing this PR for inactivity. Welcome to raise a PR in future 🙏

2023-02-24 17:54 UTC, closed without merging