Change package manager from npm to yarn
rohitdasu/projectmate pull request #294
Opened 2022-12-24 19:16 UTC by Olaleye-Blessing

### Fixes Issue
Closes #101 

### Changes proposed

- Switch the package manager from npm to yarn

2022-12-24 21:50 UTC, rohitdasu commented
@Olaleye-Blessing could you please update the readme according to `yarn`

2022-12-24 23:02 UTC, Olaleye-Blessing commented
@rohitdasu Done

2022-12-25 05:49 UTC, rohitdasu commented
@Olaleye-Blessing is there any alternative to npx in yarn universe? just curious

2022-12-25 07:25 UTC, Olaleye-Blessing commented
@rohitdasu I don't think so according to [StackOverflow answer](https://stackoverflow.com/a/66612901/11431272).

2022-12-27 19:56 UTC, rupali-codes commented on README.md
> +   yarn dev
```suggestion
   yarn run dev
```

2022-12-27 19:56 UTC, rupali-codes commented on README.md
> +   yarn dev
```suggestion
   yarn run dev
```

2022-12-27 19:58 UTC, rupali-codes requested changes
Please make the suggested changes

2022-12-27 20:26 UTC, Olaleye-Blessing commented
> Please make the suggested changes

The changes have been made.

2022-12-28 09:30 UTC, rupali-codes approved these changes

2022-12-28 10:26 UTC, JakubChorzepa commented
> @Olaleye-Blessing is there any alternative to npx in yarn universe? just curious

Hey since we have installed prisma locally we could replace ```npx prisma``` commands with ```yarn prisma```. What do you think about it?

2022-12-29 11:35 UTC, Olaleye-Blessing commented
@JakubChorzepa Is it okay to just replace all `npx` with `yarn`?

2022-12-30 16:26 UTC, rupali-codes approved these changes
LGTM

2022-12-30 17:15 UTC, JakubChorzepa approved these changes

2022-12-30 18:23 UTC, merged