feat: mates section
rohitdasu/projectmate pull request #410
Opened 2023-08-02 12:29 UTC by AryanKhubchandani

### Fixes Issue

Closes #387

### Changes proposed

- Fetch data from given api
- Add UI for mates section to show fetched data

### Note to reviewers

### Screenshots
<img width="1412" alt="image" src="https://github.com/rohitdasu/projectmate/assets/76617460/c2e0392a-fc35-44d3-a809-fc1807e519df">

2023-08-02 16:32 UTC, rohitdasu requested changes

2023-08-02 16:32 UTC, rohitdasu commented on components/MatesList/MatesList.tsx
> +          Mates
don't need heading... this is already highlighted in the sidemenu

2023-08-03 10:51 UTC, JakubChorzepa requested changes

2023-08-03 10:51 UTC, JakubChorzepa commented on components/MatesList/MatesList.tsx
> +  const { data, error } = useSWR(url, fetcher);
This is not proper way of passing url query string from internal next service.
[_Any file inside the folder pages/api is mapped to /api/*_](https://nextjs.org/docs/pages/building-your-application/routing/api-routes).
Please use url string like this `/api/user/all`

2023-08-03 11:50 UTC, rohitdasu requested changes
hi, everything looks fine but could you add a loading state in the UI?

2023-08-03 11:51 UTC, rohitdasu commented on components/MatesList/MatesList.tsx
> +  const { data, error } = useSWR(url, fetcher);
here you can get loading state... just display plain text stating 'loading'. later we can improve it

2023-08-03 11:52 UTC, rohitdasu commented on components/MatesList/Mate.tsx
> +            `https://avatars.dicebear.com/api/initials/${mate.name}.png?backgroundColorLevel=800&fontSize=40`
can you put it in a function and use it here just to make more readable?

2023-08-03 15:41 UTC, JakubChorzepa approved these changes
LGTM :+1:

2023-08-04 18:48 UTC, rohitdasu approved these changes
LGTM

2023-08-04 18:49 UTC, merged