added Back To Top FAB
rohitdasu/projectmate pull request #444
Opened 2024-01-28 07:34 UTC by FazeenIjaz

### Fixes Issue

Closes #440 

### Changes proposed

Added a "fab back to top" button for improved user experience.

### Note to reviewers

Tested on various screen sizes and browsers to ensure responsiveness.
CSS and JavaScript have been optimized for performance.
No adverse effects on existing functionality have been observed.

### Screenshots

2024-01-28 12:09 UTC, rohitdasu requested changes
please remove the package-lock file. everything else seems good to me :)

2024-01-29 08:39 UTC, FazeenIjaz commented on package-lock.json
I had removed it.Please check it.

2024-01-29 09:41 UTC, FazeenIjaz commented
> please remove the package-lock file. everything else seems good to me :)

removed

2024-01-29 09:42 UTC, rohitdasu approved these changes

2024-01-29 09:43 UTC, merged